site_name: Neovim 中文周刊
nav:
  - 第 10 期: 010.md
  - 第 9 期: 009.md
  - 第 8 期: 008.md
  - 第 7 期: 007.md
  - 第 6 期: 006.md
  - 第 5 期: 005.md
  - 第 4 期: 004.md
  - 第 3 期: 003.md
  - 第 2 期: 002.md
  - 第 1 期: 001.md


theme: readthedocs
docs_dir: posts
plugins:
  - mkdocs-video:
      is_video: True

